#!/bin/bash
source ../build

EXERCISE_FILES="lesson-conceptcloud.md lesson-terraform.md"
EXTRA_ARTIFACTS="terraform-bwcloud.zip terraform-bwcloud-solution.zip" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution

# build zip files
zip -r terraform-bwcloud.zip terraform-bwcloud
zip -r terraform-bwcloud-solution.zip terraform-bwcloud-solution
