#!/bin/bash
source ../build

EXERCISE_FILES="lesson-conceptcloud.md lesson-terraform.md"
EXTRA_ARTIFACTS="terraform.zip terraform-solution.zip" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution

# build zip files
zip -r terraform.zip terraform
zip -r terraform-solution.zip terraform-solution
