#!/bin/bash

yum install -y bind-utils vim wget screen

## lookup public hostname
publicIP=$(line=($(ip addr show eth0 | grep "inet ")); echo \$\{line[1]\} | cut -d'/' -f1)
hostname=$(nslookup $publicIP | grep "in-addr.arpa" | cut -d'=' -f2 | tr -d ' '''  | sed s'/.$//')
echo "found public hostname $hostname"
publicmaster="https://\$\{hostname\}:8443"

# install docker
(
    echo "install docker"
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum makecache fast
    yum install -y docker-ce
    mkdir /etc/docker
    echo "{
    \"storage-driver\": \"devicemapper\"
    }" > /etc/docker/daemon.json
    sudo usermod -aG docker centos
    systemctl enable docker
    systemctl restart docker
)

# install openshift
(
    echo "install openshift"
    cd /opt
    mkdir openshift-server
    wget \
        https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-server-v1.5.1-7b451fc-linux-64bit.tar.gz \
        -O openshift-server.tar.gz
    tar -xf openshift-server.tar.gz -C openshift-server --strip-components=1
)

# configure openshift software
(
    echo "configure openshift software"
    cd /opt/openshift-server
    ./openshift start --listen='https://0.0.0.0:8443'  --public-master=$publicmaster --write-config=/opt/openshift-server/openshift.local.config/master/
    touch /etc/profile.d/openshift
    echo '#!/bin/sh'
    echo 'PATH=/opt/openshift-server:$PATH' >> /etc/profile.d/openshift
)

# start openshift in screen
(
    echo "start openshift in screen"
    cd /opt/openshift-server
    screen -S openshift -d -m ./openshift start --listen='https://0.0.0.0:8443'  --public-master=$publicmaster
)

# configure openshift instance
(
    echo "configure openshift instance"
    chmod 655 /opt/openshift-server/openshift.local.config/master/admin.kubeconfig
    PATH=/opt/openshift-server:$PATH

    oc adm policy add-scc-to-user hostnetwork\
        system:serviceaccount:default:router \
        --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig

    oadm policy add-cluster-role-to-user \
        cluster-reader system:serviceaccount:default:router\
        --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig

    oc adm router router1 --replicas=1 --service-account=router --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig
)