#!/bin/bash

yum install -y vim wget

# install docker
(
    echo "install docker"
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum makecache fast
    yum install -y docker-ce
    mkdir /etc/docker
    echo "{
    \"storage-driver\": \"devicemapper\"
    }" > /etc/docker/daemon.json
    sudo usermod -aG docker centos
    systemctl enable docker
    systemctl restart docker
)
