#!/bin/bash
set -x

# install required software
yum install -y wget vim git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct NetworkManager
yum update -y
systemctl enable NetworkManager
systemctl start NetworkManager

## lookup public hostname
#publicIP=$(line=($(ip addr show eth0 | grep "inet ")); echo $${line[1]} | cut -d'/' -f1)
privateIP=$(line=($(ip addr show eth0 | grep "inet ")); echo $${line[1]} | cut -d'/' -f1)
publicIP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
hostname=$(nslookup $publicIP | grep "in-addr.arpa" | cut -d'=' -f2 | tr -d ' '''  | sed s'/.$//')
echo "found public hostname $hostname"
publicmaster="https://$${hostname}:8443"

# install ansible from epel
yum install -y epel-release
sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
yum -y --enablerepo=epel install ansible pyOpenSSL

# clone openshift-ansible 
cd /opt/
git clone https://github.com/openshift/openshift-ansible
cd /opt/openshift-ansible

# install docker
yum install -y docker
sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16"' \
/etc/sysconfig/docker
systemctl enable docker
systemctl restart docker

# configure SSH accessability
echo "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAsDubhRsskjRXSSVuzIovapsySZZwLJyjJE2sSRQy0pYJlYNA
pXB3ALwDWv+PU+Zcrb/Zvx86edYB7tEZGkKG0ULFP7xJrz6t1FAFJJ5bPdzMg8kH
qZeS/3nW94KzkyjM6OWA4V8nZUf7k9SX/AdhLDfZweIOfOVCg8B+oQQe33t95FAl
h2wnoDqZUTGJJStjGMnzS+pV7UR8Iu/nGqav+LRlupxxCDHhDNOWnqOVMJq2/0/E
FlSk3FOMBNEFXOEdo6/DkG1qndrF3b1pF4H/F088Rph58c8rHivyrpYCvwkkAnDj
lBuOb1TDl5hclzKDDQe9s+Fto6ixz6gK7fHBewIDAQABAoIBABrnbq2aYWqMjQrA
qTKWofh/auTrD4LwAsPnC7c4Wy3k89+cYwEeszwsd8KroyDm2R05Xa+cv9ubvT3N
NCzbHSPTMrOxNfqH8heog7B8cGd4TsyLoxzT5AAWhKfSj0GXB/lCGDPPx/7hR1nh
KbazFbWfbSH5NccBZO8iMvK341Kwka09KB6z1DaWuIpPjUxCKhRUcKFo5ERS9bwJ
mAi5qABsnX54te110a7yIyOGDpQqrAE/fDLYNKVjW14fES+vvUuH8uQeZnqTmd29
6ClB+L3oXfaKAY4reCeKi7dZUVbg4xM2sOP+jl80/7KCfk6w+eFFUpHMt78NzvhQ
rUZv5hkCgYEA39xlLRAJpGQ6dD8RDazAu5yEUki4JXlC6CPwIgIAss6of6hXZ1TK
ifbbhcQj9YFpPhcmuudZXPl1frd59qYtb5br5Tg8aAzFcp16QYscFkfrHtaXQ+jz
mNFcjHcngAJ91tONlvACTAh89ZtUgLOEBPAUdtg0GRiywEmM5K2/Ud8CgYEAyYi6
ZZlxVGy4ZR1iBWp1swM7ML1a7rBCG4gWQlzy1ZQqmv8MZze4urp5R3CP/zikLOOr
hOoxXA8vMftfhNsqYSC3hlKhrkh2+vDYbsdso4xzwIhj33f064xGKyNr7zIWAsxv
LpWHMr+YdAH94fLmFDoWxTRhbLP2euyKab81G+UCgYA4Ze87hiHXv8SWStlCB7ba
zVjs3hM+pak8kOlLuBNy+Ouslb3Hc64/SekOb1bb4EmicfS4+9YgvVxjm1fn0v/5
cB1oN13InQcVlCUb5C8kUeQjdc7QNh1A7+YQIWjbMEWB3PR8BWWewDizK/oDHrbx
A4c0Vc3yUK2gEiej6T4dIwKBgQCyojjl2W50sLF5HuRFfKm69MBAYXb6Xs0Z7jQc
upqb6WsiW7O4wdFB4guh4Qoh5SjQiTT86UC7ItJocTGnZ0RXN1K1AwVAoAamQ1j0
SFvpU5M+Myaja4ZySrHfhtQi/rg33tEl73AY8W7GVQWeg1ig0SRhxB4e5h0xs/yz
4sHGaQKBgDSUeeRKPkrHE+XzWdVCQmTcQdmzDB1eblCRHkrps5vtqmGhZeLj4n9+
8gAxSwCTYeskR6zogxueZkoEGJIiSAcUtddjVsxMAwZ+DRcUBGELZBR/xVjO9FlQ
OqEexCHHNOxJlD0m6WAkBwG3+pVij7VmHKJkvjEF2YorVRWS8dnP
-----END RSA PRIVATE KEY-----" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
echo "Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null" > /root/.ssh/config

# configure hosts file
echo "127.0.0.1 localhost 
$$privateIP master
${node1_ip} node1
${node2_ip} node2
${node3_ip} node3
" > /etc/hosts

# wait for nodes ...
(
    echo "waiting for nodes ..."
    for node in node1 node2 node3; do
        ssh centos@$node sudo chown centos /etc/hosts
        status=$?
        while (( $status > 0 )); do
            echo "node $node not available."
            sleep 1
            ssh centos@$node sudo chown centos /etc/hosts
            status=$?
        done
        echo "node $node is now available."
    done
    echo "Nodes are online! Let's go on..."
)

# copy hosts to nodes
for node in node1 node2 node3; do
    scp /etc/hosts centos@$node:/etc/hosts
done

# configure and run ansible
echo "
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=centos
ansible_become=true

openshift_deployment_type=origin

openshift_disable_check=memory_availability,disk_availability,docker_storage_driver,docker_storage

[masters]
master openshift_public_hostname=\"$$hostname\" openshift_public_ip=\"$$publicIP\"  openshift_hostname=\"master\"
[etcd]
master openshift_hostname=\"master\"
[nodes]
master openshift_node_labels=\"{'region': 'infra','zone': 'default'}\" openshift_schedulable=true openshift_hostname=\"master\" openshift_public_hostname=\"$$hostname\" openshift_public_ip=\"$$publicIP\"
node1 openshift_node_labels=\"{'region': 'primary', 'zone': 'default'}\" openshift_hostname=\"node1\"
node2 openshift_node_labels=\"{'region': 'primary', 'zone': 'default'}\" openshift_hostname=\"node2\"
node3 openshift_node_labels=\"{'region': 'primary', 'zone': 'default'}\" openshift_hostname=\"node3\"
" > /etc/ansible/hosts
ansible-playbook /opt/openshift-ansible/playbooks/byo/config.yml
