#!/bin/bash
cat README.md > exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

cat lesson-kubernetes.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md


cat lesson-reliability_availability.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

pandoc --latex-engine=xelatex exercise.md -t latex -o exercise.pdf
rm exercise.md

pandoc --latex-engine=xelatex solution.md -t latex -o solution.pdf
