#!/bin/bash
source ../build

EXERCISE_FILES="lesson-reliability_availability.md lesson-kubernetes.md"
#EXERCISE_FILES="lesson-reliability_availability.md"
EXTRA_ARTIFACTS="" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution
buildSlides
