#!/bin/bash
source ../build

EXERCISE_FILES="lesson-swarm.md lesson-rancher.md"
EXTRA_ARTIFACTS="terraform-dockernodes.zip terraform-rancher.zip" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution
buildSlides

# build zip files
zip -r terraform-dockernodes.zip terraform-dockernodes
zip -r terraform-rancher.zip terraform-rancher
