#!/bin/bash
cat README.md > exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

cat lesson-swarm.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

cat lesson-rancher.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

pandoc --latex-engine=xelatex exercise.md -t latex -o exercise.pdf
rm exercise.md

pandoc --latex-engine=xelatex solution.md -t latex -o solution.pdf

zip -r terraform-dockernodes.zip terraform-dockernodes
zip -r terraform-rancher.zip terraform-rancher
