#!/bin/bash
source ../build

EXERCISE_FILES="lesson-openstacknetworking.md lesson-multitier.md lesson-loadbalancing.md"
EXTRA_ARTIFACTS="" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution
