#!/bin/bash
cat README.md > exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

cat lesson-containers.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

cat lesson-mediawiki_docker.md >> exercise.md 
echo "\newpage" >> exercise.md
echo "" >> exercise.md

pandoc --latex-engine=xelatex exercise.md -t latex -o exercise.pdf
rm exercise.md

pandoc --latex-engine=xelatex solution.md -t latex -o solution.pdf

zip -r dockerfiles.zip dockerfiles
