#!/bin/bash
source ../build

EXERCISE_FILES="lesson-containers.md lesson-mediawiki_docker.md"
EXTRA_ARTIFACTS="dockerfiles.zip" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution

# build zip files
zip -r dockerfiles.zip dockerfiles
