#!/bin/bash
source ../build

EXERCISE_FILES="lesson-openstack.md lesson-firststeps.md lesson-mediawiki.md"
EXTRA_ARTIFACTS="" # excluding: exercise.pdf, solution.pdf

buildExercise
buildSolution
buildSlides