#!/bin/bash
sudo -s

apt-get update
apt-get install -y apache2 php5 php5-mysql

service apache2 restart

cd /var/www/html
wget -O mediawiki.tar.gz https://releases.wikimedia.org/mediawiki/1.28/mediawiki-1.28.2.tar.gz
mkdir wiki
tar xfvz mediawiki.tar.gz --strip 1 -C wiki

echo '<?php
if ( !defined( "MEDIAWIKI" ) ) {
	exit;
}
$wgSitename = "Clouds Lecture Wiki";
$wgMetaNamespace = "Clouds_Lecture_Wiki";
$wgScriptPath = "/wiki";
$wgServer = "http://${public_ip}";
$wgResourceBasePath = $wgScriptPath;
$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO
$wgEmergencyContact = "";
$wgPasswordSender = "";
$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;
$wgDBtype = "mysql";
$wgDBserver = "${database_ip}";
$wgDBname = "wikidb";
$wgDBuser = "wikiuser";
$wgDBpassword = "geheim";
$wgDBprefix = "";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
$wgDBmysql5 = false;
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];
$wgEnableUploads = false;
$wgUseInstantCommons = false;
$wgPingback = true;
$wgShellLocale = "en_US.utf8";
$wgLanguageCode = "en";
$wgSecretKey = "fd2307b3fe875e4c9ce2774a1465b0bc979ec433e66aba29f7a76293acc8f5b4";
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = "24749ee8bf5621a2";
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
$wgDiff3 = "/usr/bin/diff3";
$wgDefaultSkin = "vector";
wfLoadSkin( "CologneBlue" );
wfLoadSkin( "Modern" );
wfLoadSkin( "MonoBook" );
wfLoadSkin( "Vector" );
?>' > /var/www/html/wiki/LocalSettings.php
